<?xml version='1.0'?>

<robot name="linked_balls" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:property name="mass_1" value="0.06" />
	<xacro:property name="mass_2" value="0.03" />
	<xacro:property name="bar_mass" value="0.01" />
	<xacro:property name="radius_1" value="0.1" />
	<xacro:property name="radius_2" value="0.07" />
	<xacro:property name="bar_radius" value="0.02" />
	<xacro:property name="bar_length" value="0.5" />

	<xacro:macro name="ball" params="link_name radius mass color:=Blue">
		<link name="${link_name}">
			<inertial>
				<mass value="${mass}" />
				<xacro:ball_inertia mass="${mass}" radius="${radius}" />
			</inertial>
			<visual name="${link_name}_visual">
				<geometry>
					<sphere radius="${radius}" />
				</geometry>
			</visual>
			<collision name="${link_name}_collision">
				<geometry>
					<sphere radius="${radius}" />
				</geometry>
				<surface>
					<bounce>
						<restitution_coefficient>0.5</restitution_coefficient>
						<threshold>0</threshold>
					</bounce>
				</surface>
			</collision>
		</link>
		<gazebo reference="${link_name}">
			<material>Gazebo/${color}</material>
			
		</gazebo>
	</xacro:macro>

	<xacro:macro name="bar" params="link_name radius length mass relative_offset:=0">
		<xacro:property name="bar_geometry">
			<geometry>
				<cylinder length="${length}" radius="${radius}" />
			</geometry>
		</xacro:property>
		<xacro:property name="bar_origin">
			<origin xyz="${relative_offset * length} 0 0" rpy="0 ${pi/2} 0" />
		</xacro:property>
		<link name="${link_name}">
			<inertial>
				<mass value="${mass}" />
				<inertia ixx="${0.5 * mass * radius * radius}" ixy="0" ixz="0" iyy="${mass * (3 * radius * radius + length * length) / 12 + mass * relative_offset * relative_offset * length * length}" iyz="0" izz="${mass * (3 * radius * radius + length * length) / 12 + mass * relative_offset * relative_offset * length * length}" />
			</inertial>
			<visual name="${link_name}_visual">
				<xacro:insert_block name="bar_origin" />
				<xacro:insert_block name="bar_geometry" />
			</visual>
			<collision name="${link_name}_collision">
				<xacro:insert_block name="bar_origin" />
				<xacro:insert_block name="bar_geometry" />
			</collision>
		</link>
		<gazebo reference="${link_name}">
			<material>Gazebo/Gray</material>
		</gazebo>
	</xacro:macro>

	<xacro:macro name="ball_inertia" params="mass radius">
		<xacro:property name="I" value="${0.4 * mass * radius * radius}" />
		<inertia ixx="${I}" ixy="0" ixz="0" iyy="${I}" iyz="0" izz="${I}" />
	</xacro:macro>

	<xacro:ball
		link_name="ball_1"
		radius="${radius_1}"
		mass="${mass_1}" />
	<xacro:ball
		link_name="ball_2"
		radius="${radius_2}"
		mass="${mass_2}"
		color="Orange" />
	<xacro:bar
		link_name="bar"
		radius="${bar_radius}"
		length="${bar_length}"
		mass="${bar_mass}"
		relative_offset="0.5" />
	
	<joint name="bar_joint_1" type="continuous">
		<origin xyz="0 0 0" rpy="0 0 0" />
		<parent link="ball_1" />
		<axis xyz="1 0 0" />
		<child link="bar" />
		<dynamics damping="0.0" friction="0" />
	</joint>
	<joint name="bar_joint_2" type="continuous">
		<origin xyz="0.5 0 0" rpy="0 0 0" />
		<parent link="bar" />
		<child link="ball_2" />
		<!-- axis xyz="1 0 0" /-->
	</joint>

	<gazebo>
		<plugin name="force_control" filename="libforce_control.so">
			<link>ball_1</link>
		</plugin>
		<plugin name="force_control2" filename="libforce_control.so">
			<link>ball_2</link>
			<force_topic>command/wrench_2</force_topic>
			<odom_topic>odometry_2</odom_topic>
		</plugin> 
	</gazebo>

</robot>